[colors]
bg           = #cc0a0809
bg-alt       = #cc140b10
wine         = #ff1e56
wine-dim     = #8b1e3f
wine-glow    = #ff3366
dark-text    = #0a0809

[bar/brourian]
width = 100%
height = 28
offset-x = 0%
offset-y = 10

background = ${colors.bg}
foreground = ${colors.wine}

border-size = 0
radius = 16

modules-left = i3 player
modules-center = date
modules-right = system-status tray

separator = ""
padding-left = 2
padding-right = 2

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=12;3"

enable-ipc = true

; ─── i3 ───
[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true

format-prefix = ""
format-prefix-foreground = ${colors.wine}
format-suffix = ""
format-suffix-foreground = ${colors.wine}
label-background = ${colors.bg-alt}
label-padding = 2
label-margin = 0

label-focused = ""
label-focused-foreground = ${colors.wine}
label-focused-padding = 1

label-visible = ""
label-visible-foreground = ${colors.wine-dim}
label-visible-padding = 1

label-unfocused = ""
label-unfocused-foreground = ${colors.wine-dim}
label-unfocused-padding = 1

label-urgent = ""
label-urgent-foreground = ${colors.wine-glow}
label-urgent-padding = 1

; ─── Reproductor (solo play/pause, píldora normal) ───
[module/player]
type = custom/script
exec = ~/.config/polybar/scripts/player.sh
interval = 2

format-prefix = ""
format-prefix-foreground = ${colors.wine}
format-suffix = ""
format-suffix-foreground = ${colors.wine}
label-background = ${colors.bg-alt}
label-padding = 2
label-margin = 0

format = <label>
label = %output%
; El color del texto lo hereda del foreground de la barra (rojo neón)

; ─── Fecha central ───
[module/date]
type = internal/date
interval = 1.0

date = %a %d %b
time = %H:%M

format-prefix = ""
format-prefix-foreground = ${colors.wine}
format-suffix = ""
format-suffix-foreground = ${colors.wine}
label-background = ${colors.wine}
label-padding = 2
label-margin = 2

label = "󰥔 %time%  󰃭 %date%"
label-foreground = ${colors.dark-text}

; ─── Sistema ───
[module/system-status]
type = custom/script
exec = ~/.config/polybar/scripts/system-status.sh
interval = 2

format-prefix = ""
format-prefix-foreground = ${colors.wine}
format-suffix = ""
format-suffix-foreground = ${colors.wine}
label-background = ${colors.bg-alt}
label-padding = 2
label-margin = 0

format = <label>

; ─── Bandeja ───
[module/tray]
type = internal/tray
tray-size = 14
tray-padding = 4

format-prefix = ""
format-prefix-foreground = ${colors.wine}
format-suffix = ""
format-suffix-foreground = ${colors.wine}
tray-background = ${colors.bg-alt}
format = <tray>
